### ISSUE TITLE
NAT interface adapter with Debian 12

### ISSUE THREAD

**Issue by thierryler** [naveenrajm7/vagrant_utm#5]
**Describe the bug**

using https://github.com/naveenrajm7/utm-box/releases/download/debian-11/debian_vagrant_utm.zip 
as explained here https://naveenrajm7.github.io/vagrant_utm/ 
it works fine: vagrant up works and I can vagrant ssh

but using 
https://github.com/naveenrajm7/utm-box/releases/download/debian-12.6/debian-12.6.0-arm64-netinst-vagrant.zip 
it does not work

### Debug output

```
vagrant up
Bringing machine 'default' up with 'utm' provider...
==> default: Importing UTM virtual machine file https://github.com/naveenrajm7/utm-box/releases/download/debian-12.6/debian-12.6.0-arm64-netinst-vagrant.zip...
    default: IMPORTANT: Due to limited UTM API support, this plugin does not know when the download is finished.
    default: 1. Headover to UTM and confirm to download UTM file.
    default: 2. Make sure the file is loaded and exists as last VM in UTM list (UI).
    default: 3. If the downloaded VM file name is same as existing VM, UTM will cause unexpected behavior.
    default: Change VM, make sure the VM is last in the list and then continue.
    default: "Are you sure the file 'https://github.com/naveenrajm7/utm-box/releases/download/debian-12.6/debian-12.6.0-arm64-netinst-vagrant.zip' is loaded in UTM and exists as last VM? [y/N] y
==> default: Setting the Vagrant machine ID to UTM VM UUID: FD3DBB9C-6EE2-4231-930E-A1C0C52B6704
==> default: Setting the name of the VM: vagrant-test-5_default_1732748123141_31707
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
The adapter to attach a forwarded port to was not found. Please
verify that the given adapter is setup on the machine as a NAT
interface.

Host port: 2200
Guest port: 22
Adapter: 1
```

### Expected behavior

It should up

### Actual behavior

But it does not :-(

### Reproduction information

**Versions (please complete the following information):**:

On MacOS Sequoia 15.1.1 on a MBP M4
with Vagrant 2.4.3 (installed with Brew)
and UTM 4.5.4
and vagrant_utm (0.0.1, global)

#### Vagrantfile

```
Vagrant.configure("2") do |config|
  config.vm.provider :utm do |u|
    # works (Debian 11)
    # u.utm_file_url = "https://github.com/naveenrajm7/utm-box/releases/download/debian-11/debian_vagrant_utm.zip"

    # Does not work (Debian 12)
    u.utm_file_url = "https://github.com/naveenrajm7/utm-box/releases/download/debian-12.6/debian-12.6.0-arm64-netinst-vagrant.zip"
  end
end
```

**Comment by naveenrajm7** [comment]
Hi @thierryler 

Thank you for trying out this plugin and reporting this issue.
Debian 12 UTM box is not ready for usage. 
The fix would be to add the network interface and publish the new image. 

But as discussed in other issues, I am changing the plugin to support vagrant box , after that we can have VM boxes in box format in the vagrant cloud (HCP).

This will be addressed when I release box in the vagrant cloud. 

Thanks!

**Comment by naveenrajm7** [comment]
Some have kindly shared the detailed fix for this issue https://github.com/naveenrajm7/utm-box/issues/1
Hope this helps.

**Comment by naveenrajm7** [comment]
@thierryler 
There is now a Vagrant box for Debian 12.
Please update your plugin to version v0.1.1 and start using vagrant boxes!

```bash
vagrant plugin update vagrant_utm
vagrant init utm/bookworm
vagrant up
```

Thanks for trying the plugin.
